apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  selector:
    matchLabels:
      run: my-web-app
  replicas: 3
  template:
    metadata:
      labels:
        run: my-web-app
    spec:
      containers:
      - name: my-web-app
        image: mohamedabdallahrashadahmed5555/my_web
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80


